[package]
name = "raft-rs"
version = "0.1.0"
edition = "2021"


[build-dependencies]
prost-build = { version = "0.11.2" }

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
prost = "0.11.2"
